# Generated by Django 5.0.3 on 2024-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepetube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='archivo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
