# Generated by Django 5.0.3 on 2024-03-22 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepetube', '0003_video_usuario_alter_video_archivo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
