# Generated by Django 5.0.3 on 2024-03-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepetube', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
